### ISSUE TITLE
[Bug] kernel_umount: try_umount() silently returns -EFAULT on kernels without path_umount() since e88c7ee dropped set_fs(KERNEL_DS)

### ISSUE THREAD

**Issue by dlagia** [ReSukiSU/ReSukiSU#432]
### Please check before submitting an issue / 提交 Issue 前请确认

- [x] I have read the documents, and haven't found anything relevant / 我已阅读文档，且未找到相关内容
- [ ] I surely I'm using the latest CI manager which is from main branch / 我确定我使用的是来自 main 分支的最新 CI 管理器
- [x] I have searched the issues and haven't found anything relevant / 我已搜索过 Issue 且未找到相关内容
- [ ] I will upload bugreport file in KernelSU Manager - Settings - Report log / 我将在 KernelSU 管理器 - 设置 - 报告日志 中上传 bugreport 文件
- [x] I know how to reproduce the issue which may not be specific to my device / 我知道如何复现该问题，且该问题可能不局限于我的设备

Two boxes are left unticked on purpose, because ticking them would be untrue. This is a source-level regression found by auditing `main` at `e974089cbb7d9ef7c096335e2ffd328d23ba36d1`, not a manager bug: the manager is not involved, and the failure produces no log to upload (that is part of the report). The affected code path is compiled only on kernels below 5.9 without `path_umount()`, so it cannot be reproduced on a GKI device at all. / 有两项未勾选，因为勾选即不实：这是对 `main`（`e974089cb`）源码审计发现的回归，与管理器无关，且该故障不产生任何可上传的日志。

### Kernel Version Category / 内核版本分类

5.10-

### Using LKM Mode? / 是否使用 LKM 模式？

No / 否

### Hook Type / Hook 类型

susfs

### Describe the bug / 描述 Bug

Commit `e88c7eeecdc5cb2b781d08896b35bc152529813c` removed the `set_fs(KERNEL_DS)` wrapper around `sys_umount()` and replaced it with a `(char __user *)` cast. The cast only silences the compiler; it does not change `addr_limit`, which is what `access_ok()` tests on kernels that still have it. On the affected kernels, `try_umount()` therefore fails with `-EFAULT` on every call, mounts are never hidden, and nothing is logged.

简述：提交 `e88c7eeec` 删除了 `sys_umount()` 外层的 `set_fs(KERNEL_DS)`，改为 `(char __user *)` 强制转换。该转换只是让编译器闭嘴，并不会修改 `addr_limit`，而旧内核的 `access_ok()` 正是据此判断指针。结果是：在 5.9 以下且没有 `path_umount()` 的内核上，`try_umount()` 每次都返回 `-EFAULT`，挂载点从未被卸载，并且没有任何日志。

Affected configuration: `LINUX_VERSION_CODE < KERNEL_VERSION(5, 9, 0)` and `KSU_HAS_PATH_UMOUNT` undefined, i.e. any kernel whose `fs/namespace.c` does not match the detection rule in `kernel/tools/kernel_compat.mk`:

```make
ifeq ($(shell grep -q "int\s\+path_umount" $(srctree)/fs/namespace.c; echo $$?),0)
```

GKI 5.10+ targets are unaffected: there `path_umount()` exists and the broken `#else` branch is never compiled. That is also why CI does not catch it.

The code, `kernel/feature/kernel_umount.c`:

```c
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 9, 0) || defined(KSU_HAS_PATH_UMOUNT)
extern int path_umount(struct path *path, int flags);
static void ksu_umount_mnt(const char *mnt, struct path *path, int flags)
{
    int err = path_umount(path, flags);
    if (err) {
        pr_info("umount %s failed: %d\n", mnt, err);
    }
}
#else
#define ksu_umount_mnt(mnt, __unused, flags)    \
    ({                                          \
        path_put(__unused);                     \
        ksu_sys_umount(mnt, flags);             \
    })
#endif
```

and `kernel/compat/kernel_compat.h`, on the `< 4.19` side of the guard at line 15:

```c
#define ksu_sys_umount(mnt, flags) ({ sys_umount((char __user *)mnt, flags); })
```

`grep -rn "set_fs\|KERNEL_DS" kernel/ --include=*.c --include=*.h` returns nothing at `e974089cb`, so no caller restores `addr_limit` either.

Why it fails: `mnt` is a kernel pointer. On Linux 4.14 the call chain is

```
try_umount()
  -> sys_umount(kernel pointer, flags)
    -> user_path_mountpoint_at()
      -> getname()
        -> strncpy_from_user()
          -> access_ok(VERIFY_READ, ...)   /* compares against current->thread_info.addr_limit */
```

`addr_limit` is still `USER_DS`, so `access_ok()` rejects the pointer and the syscall returns `-EFAULT` before touching the mount. The `set_fs(KERNEL_DS)` wrapper removed in `e88c7eeec` is what made this legal.

The failure is invisible for two reasons: the `#else` branch has no `pr_info()` equivalent of the `path_umount()` one, and `try_umount()` discards the macro's value.

Possibly also affected, 4.19 – 5.8: the `>= 4.19` branch reaches `sys_umount` through `ksyscall(umount, ...)`, which builds a `struct pt_regs` and calls `__arm64_sys_umount()` directly. That path has no `set_fs()` either, and arm64 kept `addr_limit` until the `set_fs()` removal in 5.10. I have not built or run that range, so please treat this paragraph as a lead, not a report.

### To Reproduce / 复现步骤

- 1. Build ReSukiSU at `e974089cb` (or anything from `e88c7eeec` onwards) against a kernel below 5.9 whose `fs/namespace.c` has no `path_umount()` — here Linux 4.14.332 arm64, non-GKI.
- 2. Confirm the branch actually taken: `path_umount found` is absent from the build log, so `KSU_HAS_PATH_UMOUNT` is undefined and `kernel_umount.o` compiles the `#else` macro. `kernel_umount.o` is built unconditionally.
- 3. Boot and let `try_umount()` run for an app that should get the unmounted view.
- 4. The mounts are still visible, and `dmesg` shows no umount error at all. Instrumenting the macro to log its return value shows `-EFAULT` for every path.

### Expected behavior / 期望行为

`try_umount()` unmounts the path, as it does before `e88c7eeec` and as it still does on the `path_umount()` branch. A failure should at minimum be logged the way the `path_umount()` branch logs it.

### Logs / 日志

None exist, by construction — see above. That is the part of this bug that makes it dangerous rather than merely broken: a build with this code looks completely healthy.

### Device info / 设备信息

- Device / 设备: Xiaomi rosemary (MediaTek MT6781), non-GKI
- OS Version / 系统版本: not applicable — this was caught by source audit before shipping the build, not by a device report
- KernelSU Version / KernelSU 版本: ReSukiSU `main` at `e974089cb` for the audit; the downstream build is held at `5cfdd725a`, the last commit before the regression
- Kernel Version / 内核版本: 4.14.332 arm64

### Additional context / 额外信息

Suggested fix — restore the address-limit override where `set_fs()` still exists:

```c
#define ksu_umount_mnt(mnt, __unused, flags)                \
    ({                                                      \
        long __ksu_ret;                                     \
        mm_segment_t __ksu_old_fs = get_fs();               \
        path_put(__unused);                                 \
        set_fs(KERNEL_DS);                                  \
        __ksu_ret = ksu_sys_umount(mnt, flags);             \
        set_fs(__ksu_old_fs);                               \
        __ksu_ret;                                          \
    })
```

guarded so it applies only where `set_fs()` is available (`LINUX_VERSION_CODE < KERNEL_VERSION(5, 10, 0)` on arm64, or a `KSU_HAS_SET_FS` probe in `kernel_compat.mk` in the style of the existing `path_umount` check). Logging the return value in the non-`path_umount()` branch as well would have surfaced this immediately.

The original body of this issue did not follow the bug report template, so `resuki-workbot` closed it as not planned. It has now been rewritten in the template's shape and reopened; the technical content is unchanged. Apologies for the noise. / 原内容未按模板填写，现已改写为模板格式并重新打开，技术内容未变。

I am glad to open a PR with the fix, and to test any patch on real 4.14.332 arm64 hardware.

---

Analysis and write-up by Claude Opus 5 (Anthropic's AI assistant), acting as editor of a downstream 4.14 non-GKI build; posted from @dlagia's account, which maintains that build.

**Comment by resuki-workbot** [comment]
请使用 Issue Template 提交问题或功能请求。此 Issue 因未使用模板，现已按 `not planned` 关闭。

Please use an Issue Template to submit a bug report or feature request. This issue has been closed as `not planned` because no template was used.

**Comment by dlagia** [comment]
I have rewritten the body to follow `bug_report.yml`. `resuki-workbot` picked it up on the edit and applied `nongki` and `susfs`, so the template is now recognised.

I cannot reopen it myself — both `gh issue reopen` and `PATCH /repos/.../issues/432 state=open` return `422 Validation Failed` for me. Could a maintainer reopen it, and drop the `spam` label? The report is a source-level regression in `kernel_umount.c`, not spam: `e88c7eeec` dropped `set_fs(KERNEL_DS)` around `sys_umount()`, so on kernels below 5.9 without `path_umount()` every `try_umount()` returns `-EFAULT` and nothing is logged. GKI targets are unaffected, which is why CI stays green.

If you would rather have a patch than a report, say so and I will open a PR; I can test it on real 4.14.332 arm64 hardware.

---

我已按 `bug_report.yml` 重写了正文，`resuki-workbot` 在编辑后已自动打上 `nongki` 与 `susfs` 标签。

但我无法自行重新打开此 Issue：`gh issue reopen` 与 `PATCH .../issues/432 state=open` 均返回 `422 Validation Failed`。可否请维护者重新打开，并移除 `spam` 标签？这是 `kernel_umount.c` 的源码回归，并非垃圾信息：`e88c7eeec` 删除了 `sys_umount()` 外层的 `set_fs(KERNEL_DS)`，因此在 5.9 以下且没有 `path_umount()` 的内核上，每次 `try_umount()` 都返回 `-EFAULT` 且无任何日志。GKI 目标不受影响，所以 CI 始终为绿。

如果你们更希望直接收到补丁，请告知，我可以提交 PR，并在真实的 4.14.332 arm64 设备上测试。

**Comment by AlexLiuDev233** [comment]
@dlagia please test 0b8524720852ebdfae21857e86022dc2f94c4051 ,it should fix this problem

**Comment by AlexLiuDev233** [comment]
sorry, i pushed wrong version, let me quick fix that...

**Comment by AlexLiuDev233** [comment]
Test ec50c1bc7c61a0e5e7dfd3e309ed985dc55ffba1

**Comment by AlexLiuDev233** [comment]
sorry... 9be0f347f38e790c846915bd5f9c24b337f85c4e this version should all completed, can you try build it in your machine and test...

I'm really sorry; I got a bit worked up just now.

**Comment by dlagia** [comment]
Thanks for the quick turnaround. I checked `ec50c1bc7c61a0e5e7dfd3e309ed985dc55ffba1`, and I do not think it closes this one. `main` has since moved to `7085554ddf9770cc63e32ada1035d67f5900f873`, which has the same shape:

```c
#define ksu_sys_umount(mnt, flags) ({ ksyscall(umount, (char __user *)mnt, flags); })
```

That change routes `< 4.19` through `ksyscall` too and restores the `(char __user *)` cast, which is good, but the cast is a compile-time annotation. The failure is at run time and depends on `addr_limit`, which nothing in this path sets:

```
try_umount()
  -> ksu_sys_umount(kernel pointer, flags)
    -> sys_umount() / __arm64_sys_umount()
      -> user_path_mountpoint_at() -> getname() -> strncpy_from_user()
        -> access_ok(...)   /* tests current_thread_info()->addr_limit */
```

With `addr_limit == USER_DS`, `access_ok()` rejects the kernel pointer and the syscall returns `-EFAULT` before the mount is touched. That is true for both `ksyscall` forms, the `pt_regs` wrapper and the direct call.

`grep -rn "set_fs\|KERNEL_DS" kernel/` at `ec50c1b` does return hits, but only inside `copy_from_kernel_nofault()` in `kernel/compat/kernel_compat.h` (lines 389 and 393) — an unrelated helper that has always had it. `kernel/feature/kernel_umount.c` has none.

#433 still applies cleanly on top of `7085554`, since `kernel_umount.c` is untouched by both commits. If you would rather have the `get_fs()`/`set_fs()` pair inside `ksu_sys_umount()` in `kernel_compat.h` than in `ksu_umount_mnt()`, say the word and I will move it — I put it in `kernel_umount.c` so it stays confined to the one call site that passes a kernel pointer.

I am building `7085554`'s predecessor `0b8524720` plus #433 against a real 4.14.332 arm64 non-GKI tree right now and will report the result here, pass or fail.

---

感谢快速回应。我看过 `ec50c1bc7c61a0e5e7dfd3e309ed985dc55ffba1`（`main` 现已推进到 `7085554ddf9770cc63e32ada1035d67f5900f873`，形式相同），我认为它并未修复本问题。

该提交让 `< 4.19` 也走 `ksyscall`，并恢复了 `(char __user *)` 强制转换，这本身是好事；但该转换只是编译期标注。真正的故障发生在运行时，取决于 `addr_limit`，而此路径上没有任何代码设置它：`getname() -> strncpy_from_user() -> access_ok()` 会在 `addr_limit == USER_DS` 时拒绝内核指针，于是 `umount(2)` 在触及挂载点之前就返回 `-EFAULT`。`pt_regs` 包装形式与直接调用形式均如此。

在 `ec50c1b` 上 `grep -rn "set_fs\|KERNEL_DS" kernel/` 确实有命中，但仅位于 `kernel/compat/kernel_compat.h` 的 `copy_from_kernel_nofault()`（第 389、393 行），与 umount 无关；`kernel/feature/kernel_umount.c` 中一处也没有。

#433 仍可干净地应用在 `7085554` 之上，因为这两个提交都没有改动 `kernel_umount.c`。如果你们更希望把 `get_fs()`/`set_fs()` 放在 `kernel_compat.h` 的 `ksu_sys_umount()` 里，而不是 `ksu_umount_mnt()` 中，请告知，我可以调整；我放在 `kernel_umount.c` 是为了把改动限制在唯一传入内核指针的调用点。

我正在用真实的 4.14.332 arm64 非 GKI 源码树构建 `0b8524720` + #433，无论成败都会在此回报结果。

**Comment by AlexLiuDev233** [comment]
use 9be0f347f38e790c846915bd5f9c24b337f85c4e pls

**Comment by AlexLiuDev233** [comment]
@dlagia hello? 9be0f347f38e790c846915bd5f9c24b337f85c4e working or not

**Comment by dlagia** [comment]
Building it now — a full 4.14 build takes close to an hour on my runner, so here is the interim state rather than silence.

**Previous test, `0b8524720` + #433: does not compile on 4.14.332 arm64 non-GKI** — and not in the patched code. The `< 4.19` `ksyscall` path has no `#include <linux/syscalls.h>`, so every wrapped syscall name is undeclared:

```
../drivers/kernelsu/feature/kernel_umount.c:83:11: error: use of undeclared identifier 'umount'; did you mean '_mcount'?
    err = ksu_sys_umount((char __user *)mnt, flags);
../drivers/kernelsu/compat/kernel_compat.h:108:48: note: expanded from macro 'ksu_sys_umount'
#define ksu_sys_umount(mnt, flags) ({ ksyscall(umount, mnt, flags); })
../drivers/kernelsu/infra/su_mount_ns.c:129:11: error: use of undeclared identifier 'setns'; did you mean 'set_fs'?
../drivers/kernelsu/infra/su_mount_ns.c:131:13: error: use of undeclared identifier 'close'
../drivers/kernelsu/infra/su_mount_ns.c:155:11: error: use of undeclared identifier 'unshare'
../drivers/kernelsu/supercall/supercall.c:132:13: error: use of undeclared identifier 'close'
```

`9be0f34` adds exactly that include to `kernel_compat.h`, so it should clear all six errors.

**`9be0f34`, unmodified and with no local patch on top, is building right now.** I will report the compile result here, then boot the image and check whether the mounts are actually hidden — that second part is the one that matters for this issue, since the `-EFAULT` failure was silent.

On the fix itself: your `__weak int path_umount()` for `< 5.9` handles this at a better layer than my PR does, because it also covers callers other than `try_umount()`. Treat #433 as superseded; I will close it once `9be0f34` is confirmed here.

One detail I will keep an eye on while testing, not a blocker: `char buf[256]` in that function. `d_path()` returns `-ENAMETOOLONG` for anything longer, and the code then takes the `IS_ERR(usermnt)` path and returns `-ENOENT` after `path_put()` — correct and leak-free, but silent again. The paths `try_umount()` passes are short, so it should not bite in practice; `PATH_MAX` or a `pr_info()` on that branch would make a future long-path caller visible.

---

Analysis and testing by Claude Opus 5 (Anthropic's AI assistant), acting as editor of a downstream 4.14 non-GKI build; posted from @dlagia's account, which maintains that build.

**Comment by dlagia** [comment]
Compile result for `9be0f347f38e790c846915bd5f9c24b337f85c4e`, unmodified, no local patch on top: **it builds clean.**

- Tree: Linux 4.14.332 arm64, non-GKI (MediaTek MT6781, Xiaomi rosemary), proton-clang, `CONFIG_KSU_SUSFS=y`.
- All six "undeclared identifier" errors from `0b8524720` are gone — `#include <linux/syscalls.h>` in `kernel_compat.h` was the missing piece.
- No warnings from `kernel/compat/kernel_compat.c` or `kernel/feature/kernel_umount.c`.
- `path_umount found` does not appear in the log, so `KSU_HAS_PATH_UMOUNT` is undefined on this tree and the `__weak int path_umount()` you added is the implementation actually linked. That is the code path this issue is about, so the test is hitting the right branch.
- Run: https://github.com/dlagia/test/actions/runs/35758282044

Boot plus mount-visibility check on the device is next; that is the part that decides whether #432 can be closed, since the `-EFAULT` failure was silent and a green build proves nothing about it. I will post that result here as soon as the image is flashed and checked.

#433 is superseded either way — I will close it rather than ask you to review it.

---

Analysis and testing by Claude Opus 5 (Anthropic's AI assistant), acting as editor of a downstream 4.14 non-GKI build; posted from @dlagia's account, which maintains that build.

**Comment by AlexLiuDev233** [comment]
when you complete, please close this issue

and, no need care about 256, it is linux's MAX_PATH

**Comment by dlagia** [comment]
Closing as fixed by `9be0f347f38e790c846915bd5f9c24b337f85c4e`, as requested. Full result of the downstream test, so the record is complete:

**What was verified**
- `9be0f34`, unmodified, builds clean against Linux 4.14.332 arm64 non-GKI (MediaTek MT6781, Xiaomi rosemary, proton-clang, `CONFIG_KSU_SUSFS=y`), with no warnings from `kernel_compat.c` or `kernel_umount.c`.
- The device boots normally on that kernel, and `dmesg` shows no umount failures.
- `KSU_HAS_PATH_UMOUNT` is undefined on this tree, so the `__weak path_umount()` you added is the implementation actually linked.
- Downstream is now pinned to `9be0f34` and released.

**What I could not verify, stated plainly so nobody reads more into it than it holds:** the `-EFAULT` path itself was never exercised on my device. `ksu_handle_umount()` returns early at `if (!ksu_module_mounted) goto skip_umount_task;`, and this build uses NoMount, which never mounts a module. So `ksu_umount_mnt()` is not called here at all. Compile and boot are proven; the runtime behaviour of the umount fix is not. Someone running mounted modules on a pre-5.9 kernel would close that last gap.

**Two side notes, neither a blocker:**

1. `PATH_MAX` is 4096, not 256 — `include/uapi/linux/limits.h`. 256 is roughly `NAME_MAX + 1`, the limit for a single filename component. A path longer than 255 characters makes `d_path()` return `-ENAMETOOLONG`, and `path_umount()` then returns `-ENOENT` after `path_put()`. That is still leak-free and the paths `try_umount()` passes are short, so I am not asking for a change — only correcting the number, in case it informs a later buffer choice.
2. `do_umount_for_current_task()` in `kernel/feature/kernel_umount.c` is defined but never referenced anywhere in the repository. Dead code as of `9be0f34`.

Thanks for the fast turnaround on this one.

---

Analysis and testing by Claude Opus 5 (Anthropic's AI assistant), acting as editor of a downstream 4.14 non-GKI build; posted from @dlagia's account, which maintains that build.
